create database virat_kohli_centuries
use virat_kohli_centuries

------------------------------------------------------------------------------IPL MATCH----------------------------------------------------------------------------
--1) COUNT Centuries of IPL ?
select COUNT(Matches) AS 'IPL' from IPL;
--2)TOTAL STRICK RATE OF CENTURIES IN IPL
SELECT (SUM(RUN)/SUM(BALL))*100 AS 'STRICK RATE' FROM IPL ;
SELECT AVG(RUN/BALL)*100 AS 'STRICK RATE'FROM IPL;
--3)TOTAL RUN OF CENTURIES IN TEST   
SELECT SUM(RUN) AS 'TOTAL TEST RUN OF VIRAT KOHLI'FROM IPL;
--4)TOTAL AVERAGE RUN OF CENTURIES IN IPL
SELECT AVG(RUN) AS 'AVERAGE TEST RUN OF VIRAT KOHLI'FROM IPL;
--5)TOTAL MAXIMUM RUN OF CENTURIES IN IPL
SELECT MAX(RUN) AS 'MAXIMUM TEST RUN OF VIRAT KOHLI'FROM IPL;
--6)TOTAL MINIMUM RUN OF CENTURIES IN IPL
SELECT MIN(RUN) AS 'MINIMUM TEST RUN OF VIRAT KOHLI'FROM IPL;
--7)WINING MATCHES OF CENTURIES OF IPL
SELECT * from IPL where India_Match_Result='Won';
--8)TOP 10 CENTURIES OF IPL 
SELECT TOP 10 RUN FROM IPL;
--9)COUNT OF CENTURIES OF OPPONENT IN IPL
select count(RUN) as 'NUMBER OF COUNT CENTURIES OF Opponent ',Opponent from IPL  group by Opponent
--10)TOTAL RUN OF Opponent OF IPL
select sum(RUN) as 'TOTAL RUN OF Opponent ',Opponent from IPL group by Opponent  order by sum(RUN) desc
--11)SECOND HIGHEST OF CENTURIES  IN IPL
select * FROM IPL WHERE RUN =(SELECT MAX(RUN) FROM IPL WHERE RUN<(SELECT MAX(RUN) FROM IPL))

------------------------------------------------------ODI MATCH---------------------------------------------------------------------------------------------------------------
--1) COUNT Centuries of ODI ?
select COUNT(Matches) AS 'ODI' from ODI ;
--2)TOTAL STRICK RATE OF CENTURIES IN ODI
SELECT (SUM(RUN)/SUM(BALL))*100 AS 'STRICK RATE' FROM ODI ;
--3)AVERAGE STRICK RATE OF CENTURIES IN ODI
SELECT AVG(RUN/BALL)*100 AS 'STRICK RATE'FROM ODI ;
--4)TOTAL RUN OF CENTURIES IN ODI   
SELECT SUM(RUN) AS 'TOTAL ODI RUN OF VIRAT KOHLI'FROM ODI;
--5)TOTAL AVERAGE RUN OF CENTURIES IN ODI
SELECT AVG(RUN) AS 'AVERAGE ODI RUN OF VIRAT KOHLI'FROM ODI;
--6)TOTAL MAXIMUM RUN OF CENTURIES IN ODI
SELECT MAX(RUN) AS 'MAXIMUM ODI RUN OF VIRAT KOHLI'FROM ODI;
--7)TOTAL MINIMUM RUN OF CENTURIES IN ODI
SELECT MIN(RUN) AS 'MINIMUM ODI RUN OF VIRAT KOHLI'FROM ODI;
--8)WINING MATCHES OF CENTURIES OF ODI
SELECT * from ODI where India_Match_Result='Won';
--9)TOP 10 CENTURIES OF ODI 
SELECT TOP 10 RUN FROM ODI ;
--10)COUNT OF CENTURIES OF OPPONENT IN ODI
select count(RUN) as 'NUMBER OF COUNT CENTURIES OF Opponent ',Opponent from ODI  group by Opponent
--11)TOTAL RUN OF Opponent OF ODI
select sum(RUN) as 'TOTAL RUN OF Opponent ',Opponent from ODI  group by Opponent  order by sum(RUN) desc
--12)SECOND HIGHEST OF CENTURIES  IN ODI
select * FROM ODI WHERE RUN =(SELECT MAX(RUN) FROM ODI WHERE RUN<(SELECT MAX(RUN) FROM ODI) )


------------------------------------------------------------------------------T20 MATCH----------------------------------------------------------------------------

--1) COUNT Centuries of T20 ?
select COUNT(Matches) AS 'T20' from T20 ;
--2)TOTAL STRICK RATE OF CENTURIES IN T20
SELECT (SUM(RUN)/SUM(BALL))*100 AS 'STRICK RATE' FROM T20;
--3)AVERAGE STRICK RATE OF CENTURIES IN ODI
SELECT AVG(RUN/BALL)*100 AS 'STRICK RATE'FROM T20;
--4)TOTAL RUN OF CENTURIES IN T20   
SELECT SUM(RUN) AS 'TOTAL ODI RUN OF VIRAT KOHLI'FROM T20;
--5)TOTAL AVERAGE RUN OF CENTURIES IN T20
SELECT AVG(RUN) AS 'AVERAGE ODI RUN OF VIRAT KOHLI'FROM T20;
--6)TOTAL MAXIMUM RUN OF CENTURIES IN T20
SELECT MAX(RUN) AS 'MAXIMUM ODI RUN OF VIRAT KOHLI'FROM T20;
--7)TOTAL MINIMUM RUN OF CENTURIES IN T20
SELECT MIN(RUN) AS 'MINIMUM ODI RUN OF VIRAT KOHLI'FROM T20;
--8)WINING MATCHES OF CENTURIES OF T20
SELECT * from T20 where India_Match_Result='Won';
--9)TOP 10 CENTURIES OF T20 
--SELECT TOP 10 RUN FROM T20 ;
--10)COUNT OF CENTURIES OF OPPONENT IN T20
select count(RUN) as 'NUMBER OF COUNT CENTURIES OF Opponent ',Opponent from T20 where Opponent in ('Afghanistan')  group by Opponent
--11)TOTAL RUN OF Opponent OF T20
select sum(RUN) as 'TOTAL RUN OF Opponent ',Opponent from T20 where Opponent in ('Afghanistan') group by Opponent  order by sum(RUN) desc



-----------------------------TEST MATCH-----------------------------------------------------------------------------------------------

--1) COUNT Centuries of TEST ?
select COUNT(Matches) AS 'TEST' from TEST;
--2)TOTAL STRICK RATE OF CENTURIES IN TEST
SELECT (SUM(RUN)/SUM(BALL))*100 AS 'STRICK RATE' FROM TEST;
SELECT AVG(RUN/BALL)*100 AS 'STRICK RATE'FROM TEST;
--3)TOTAL RUN OF CENTURIES IN TEST   
SELECT SUM(RUN) AS 'TOTAL TEST RUN OF VIRAT KOHLI'FROM TEST;
--4)TOTAL AVERAGE RUN OF CENTURIES IN TEST
SELECT AVG(RUN) AS 'AVERAGE TEST RUN OF VIRAT KOHLI'FROM TEST;
--5)TOTAL MAXIMUM RUN OF CENTURIES IN TEST
SELECT MAX(RUN) AS 'MAXIMUM TEST RUN OF VIRAT KOHLI'FROM TEST;
--6)TOTAL MINIMUM RUN OF CENTURIES IN TEST
SELECT MIN(RUN) AS 'MINIMUM TEST RUN OF VIRAT KOHLI'FROM TEST;
--7)WINING MATCHES OF CENTURIES OF TEST
SELECT * from TEST where India_Match_Result='Won';
--8)TOP 10 CENTURIES OF TEST 
SELECT TOP 10 RUN FROM TEST;
--9)COUNT OF CENTURIES OF OPPONENT IN TEST
select count(RUN) as 'NUMBER OF COUNT CENTURIES OF Opponent ',Opponent from TEST group by Opponent
--10)TOTAL RUN OF Opponent OF TEST
select sum(RUN) as 'TOTAL RUN OF Opponent ',Opponent from TEST  group by Opponent  order by sum(RUN) desc
--11)SECOND HIGHEST OF CENTURIES  IN TEST
select * FROM TEST WHERE RUN =(SELECT MAX(RUN) FROM TEST WHERE RUN<(SELECT MAX(RUN) FROM TEST ) )










